permalink: /blog/:categories/:title

exclude:
    - .editorconfig
    - .gitattributes
    - .gitignore
    - tasks
    - CNAME
    - less
    - node_modules
    - Gemfile
    - Gemfile.lock
    - gulpfile.js
    - package.json

timezone: Asia/Tokyo

encoding: 'UTF-8'
